# source common.sh

# rabbitmq_password=$1

# if [ -z "${rabbitmq_password}" ]; then
# echo -e "\e[31mMisiing rabbit password\e[0m"
# exit 1
# fi

# print_header "downloading repo code"
# curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash &>>{log_file}
# status_check $?

# print_header "installing erlang"
# yum install erlang -y &>>{log_file}
# status_check $?

# print_header "downloading app code"
# curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash &>>{log_file}
# status_check $?

# print_header "installing rabbitmq"
# yum install rabbitmq-server -y &>>{log_file}
# status_check $?

# print_header "starting rabbitmq server"
# systemctl enable rabbitmq-server &>>{log_file}
# systemctl start rabbitmq-server  &>>{log_file}
# status_check $?

# print_header "Add Application User"
# rabbitmqctl list_users | grep roboshop &>>${log_file}
# if [ $? -ne 0 ]; then
#   rabbitmqctl add_user roboshop ${rabbitmq_password} &>>${log_file}
# fi
# status_check $?

# print_header "Configure Permissions for App User"
# rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"  &>>${log_file}
# status_check $?

- name: setup erlang repositories
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: setup rabbitmq repositories
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: install rabbitmq and erlang
  ansible.builtin.yum:
    name:
    - erlang
    - rabbitmq-server
    state: installed

- name: start rabbitmq
  ansible.builtin.systemd :
    name: rabbitmq-server
    state: started
    enabled: true

- name : add rabbitmq user and give permissions
  community.rabbitmq.rabbitmq_user:
    user: "{{ lookup ('amazon.aws.aws_ssm', '{{env}}.{{component}}.ampq_user', region='us-east-1') }}"
    password: "{{ lookup ('amazon.aws.aws_ssm', '{{env}}.{{component}}.ampq_password', region='us-east-1') }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present