# source common.sh

# mysql_root_password=$1
# if [ -z "${mysql_root_password}" ]; then
#   echo -e "\e[31mMissing MySQL Root Password argument\e[0m"
#   exit 1
# fi

# print_header "disabling exiting  mysql"
# dnf module disable mysql -y  &>>${log_file}
# status_check $?

# print_header "loading mysql repositories"
# cp ${code_dir}/configs/mysql.repo /etc/yum.repos.d/mysql.repo  &>>${log_file}
# status_check $?

# print_header "installing mysql"
# yum install mysql-community-server -y  &>>${log_file}
# status_check $?

# print_header "starting mysql server"
# systemctl enable mysqld  &>>${log_file}
# systemctl start mysqld  &>>${log_file}
# status_check $?

# print_header "setting root password mysql"
# echo show databases | mysql -uroot -p${mysql_root_password}  &>>${log_file}
# if [ $? -ne 0 ]; then
# mysql_secure_installation --set-root-pass ${mysql_root_password}  &>>${log_file}
# fi
# status_check $?

- name: disable mysql repository
  ansible.builtin.shell: dnf module disable mysql -y

- name : setup mysql repository
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name : install mysql 
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name : start mysql
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: true

- name: setup mysql root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
  ignore_errors: true