- name : installing node exporter
  ansible.builtin.unarchive:
    src : "{{exporter_url}}"
    dest : /opt
    remote_src : yes

- name : copy node exporter systemd files
  ansible.builtin.template:
    src: exporter.service
    dest : /etc/systemd/system/exporter.service

- name : restore node exporter
  ansible.builtin.systemd:
    name : node_exporter
    state : restarted
    enabled : true
    daemon_reload : true
