- name : prometheus configuration
  ansible.builtin.import_tasks:
    file : server.yml
  when : prometheus_server

- name : node exporter configuration
  ansible.builtin.import_tasks:
    file : server.yml
  when : node_exporter
