- name : update prometheus configuration
  ansible.builtin.template:
    src : prometheus.yml
    dest : /opt/prometheus/prometheus.yml

- name : update prometheus_alerts configuration
  ansible.builtin.template:
    src : "{{item}}"
    dest : /opt/prometheus/{{item}}
  loop: "{{ alert_files }}"

- name : restart prometheus 
  ansible.builtin.systemd:
    name : prometheus
    state : restarted
    enabled : true

- name : checking prometeheus started or not
  ansible.builtin.shell: netstat -anptlu | grep 9090

- name : update alert manager configuration
  ansible.builtin.template:
    src : alertmanager.yml
    dest : /opt/alertmanager/alertmanager.yml

- name : restart alert manager 
  ansible.builtin.systemd:
    name : alertmanager
    state : restarted
    enabled : true

- name : checking prometeheus started or not
  ansible.builtin.shell: netstat -anptlu | grep 9093
