# java (){
# print_header "Installing maven "
# yum install maven -y  &>>${log_file}
# status_check $?

# app_user_setup

# print_header "installing dependencies"
# mvn clean package   &>>${log_file}
# mv target/$component-1.0.jar $component.jar  &>>${log_file}
# status_check $?

# schema_setup
# systemd_setup

# }

# - name: installing maven
#   ansible.builtin.yum:
#     name: maven
#     state: installed

- name: Install Java
  ansible.builtin.yum:
    name: java-11-openjdk
    state: installed

- name: app_user_setup
  ansible.builtin.import_tasks:
    file: app_user.yml

# - name: installing maven dependencies
#   ansible.builtin.shell: mvn clean package; mv target/{{component}}-1.0.jar {{component}}.jar
#   args:
#     chdir: /app

- name : schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml
  when: schema_type is defined

- name : systemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml



