# nodejs () {

# print_header "downloading code"
# curl -sL https://rpm.nodesource.com/setup_lts.x | bash &>>${log_file}
# status_check $?

# print_header "installing package"
# yum install nodejs -y &>>${log_file}
# status_check $?

# app_user_setup

# print_header "installing new code"
# npm install &>>${log_file}
# status_check $?

# schema_setup

# systemd_setup

# }

- name : download and extract code nodejs repo
  ansible.builtin.shell : curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name : install nodejs 
  ansible.builtin.yum:
    name : nodejs
    state: installed

- name : setup app user
  ansible.builtin.import_tasks:
    file: app_user.yml

- name : setup nodes dependencies
  community.general.npm:
    path: /app

- name : schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml
  when: schema_type is defined

- name : systemd setup
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
