# schema_setup () {

# if [ "${schema_type}" == "mongo" ]; then

# print_header "loading mogo repositories"
# cp ${code_dir}/configs/mongodb.repo /etc/yum.repos.d/mongodb.repo &>>${log_file}
# yum install mongodb-org-shell -y &>>${log_file}
# status_check $?

# print_header "loading schema"
# mongo --host mongodb.sstech.store </app/schema/$component.js &>>${log_file}
# status_check $?

# elif [ "${schema_type}" == "mysql" ]; then

# print_header "installing mysql"
# yum install mysql -y &>>${log_file}
# status_check $?

# print_header "loading mysql schema"
# mysql -h mysql.sstech.store -uroot -p${mysql_root_password} < /app/schema/$component.sql &>>${log_file}
# status_check $?
# fi
# }

- name: mongodb schema
  when: schema_type == "mongo"
  block:
    - name: copying monogodb repositories
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: install monodb client
      ansible.builtin.yum:
        name: mongodb-org-shell

    - name : install docdb aws pem file
      ansible.builtin.get_url:
        url: https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem
        dest: /app/rds-combined-ca-bundle.pem


    - name: loading mongodb schema
      # ansible.builtin.shell: mongo --host mongodb-dev.sstech.store </app/schema/{{component}}.js
      # ansible.builtin.shell : mongo --ssl --host dev-docdb.cluster-capdsiq5nfpo.us-east-1.docdb.amazonaws.com:27017 --sslCAFile rds-combined-ca-bundle.pem --username admin1 --password <insertYourPassword>
      ansible.builtin.shell : mongo --ssl --host {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb_endpoint', region='us-east-1') }}:27017 --sslCAFile rds-combined-ca-bundle.pem --username {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.user', region='us-east-1') }} --password {{ lookup('amazon.aws.aws_ssm', '{{env}}.docdb.pass', region='us-east-1') }} </app/schema/{{component}}.js


- name: mysql schema
  when: schema_type == "mysql"
  block:
    - name: install mysql
      ansible.builtin.yum:
        name: mysql
        state: installed
    - name: loading mysql schema
      ansible.builtin.shell: mysql -h mysql-dev.sstech.store -uroot -pRoboShop@1 < /app/schema/{{component}}.sql

