route:
  group_by: ['alertname']
  group_wait: 20s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
    - to: shankarsrinivasnew@gmail.com
      from: shankarsrinivasnew@gmail.com
      smarthost: "email-smtp.us-east-1.amazonaws.com:587"
      auth_username: "{{ses_auth_username}}"
      auth_password: "{{ses_auth_password}}"
      require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']