groups:
- name: roboshop
  rules:
  - alert: Server Down
    expr: up < 1
    for: 20s
    labels:
      severity: critical
    annotations:
      summary: Server Down
  
  - alert: High CPU Usage
    expr: 100 - ( avg by (Name) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100 ) > 80
    for: 20s
    labels:
      severity: critical
    annotations:
      summary:  High CPU Usage 