groups:
- name: roboshop-server
  rules:
  {% for component in components %}

  - alert: roboshop {{component.name}} service down alert 
    expr: node_systemd_unit_state{name="{{component.service}}.service", state="active"} < 1
    for: 20s
    labels:
      severity: critical
      appName: {{component.name}}
    annotations:
      summary: {{component.service}} service is  Down
  {% endfor %}